### ISSUE TITLE
accountblock import error in linux

### ISSUE THREAD

**Issue by Gabrielpatrola** [vitelabs/vite.js#33]
When I try to use the lib in a linux environment, I got the following error:

```
node_modules/@vite/vitejs/distSrc/index.ts:6:32 - error TS2307: Cannot find module './accountblock/index' or its corresponding type declarations.

import * as _accountBlock from './accountblock/index';

node_modules/@vite/vitejs/distSrc/viteAPI/index.ts:5:118 - error TS2307: Cannot find module './../accountblock/utils' or its corresponding type declarations.

import { Default_Contract_TransactionType, encodeContractList, getTransactionType, decodeContractAccountBlock } from './../accountblock/utils';
```

But in Windows everything works fine. I'm using the latest version

**Comment by soliury** [comment]
Can you put you code here with more details?

**Comment by Gabrielpatrola** [comment]
`
import {HTTP_RPC} from '@vite/vitejs-http';
import {ViteAPI, wallet, accountBlock} from '@vite/vitejs';
import {Address, BigInt, AddressObj} from '@vite/vitejs/distSrc/accountBlock/type';
import {Int64, Uint64, RPCResponse} from '@vite/vitejs/distSrc/utils/type';
import {getLatestCycleTimestampFromNow} from './timeUtil';
`

This is the imports in the main.ts

**Comment by JohnGarnham** [comment]
It looks like a simple typo. Some places are referencing accountBlock and other places are referencing accountblock.

For a quick fix I went through node_modules and changed s/accountblock/accountBlock/g and all of the errors went away.

**Comment by JeanOUINA** [comment]
Can someone fix it ? It’s annoying to have errors in the typescript build output

**Comment by Gabrielpatrola** [comment]
>  Maybe because Linux is case sensitive and Windows isn't?

Yes, it is the problem.

**Comment by KaffinPX** [comment]
This should closed now

**Comment by JohnGarnham** [comment]
It looks like that accountblock typo error somehow got reintroduced. In some places it is referenced as accountblock and in other places accountBlock. On Windows this is no problem because it's case insensitive, but in Linux this is a bug. This is latest \@vite/vitejs @2.3.16 pulled just one minute ago.

/node_modules/@vite/vitejs/distStr/viteAPI/index.ts:5

```import { Default_Contract_TransactionType, encodeContractList, getTransactionType, decodeContractAccountBlock } from './../accountblock/utils';```

But directory is accountBlock not accountblock. I thought this was fixed in a recent release, don't know how it got reintroduced ?'
