### ISSUE TITLE
Subscribe automatically after ws reconnect

### ISSUE THREAD

**Issue by KaffinPX** [vitelabs/vite.js#55]

**Comment by JeanOUINA** [comment]
Yes please, I’m currently using some sketchy code that replaces how events work internally, would be cool if it was natively supported.

**Comment by KaffinPX** [comment]
Any update?

**Comment by AllenLiuxt** [comment]
Opened #71 to address this

**Comment by AllenLiuxt** [comment]
Solved in 2.3.19-alpha.3
