### ISSUE TITLE
module imports

### ISSUE THREAD

**Issue by decentraliser** [vitelabs/vite.js#9]
Hi, 

I'm getting into vite.js and noticing that most of the imports are broken in the @vite\vitejs\dist\es5\ folder

for example:

```
Cannot find module 'utils/tools'
at Object.<anonymous> (C:\dev\vite-server\node_modules\@vite\vitejs\dist\es5\utils\encoder.js:4:15)
```
the import is:
`var tools_1 = require("utils/tools");
`
However what would work for me is:
`var tools_1 = require("./tools");`

Does it have anything to do with my configuration?
I am using node v10.15.1

Thanks

**Comment by woodghost** [comment]
Hi there, please do not import '@Vite\vitejs\dist\es5\' folder directly in your project, currently this way hasn't been supported yet. You should import the whole package to fix this

**Comment by decentraliser** [comment]
OK, thanks for the answer!
